name: Build on PR for paytm

on: 
  pull_request:
    branch: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Generate prisma cliwnt
        run: npm run db:generate
        
      - name: Install depencies in user-app
        run: npm run user-app:install
      - name: Install depencies in merchant-app
        run: npm run marchant-app:install
        

      - name: Install Dependecies
        run: npm install

      - name: Run Build
        run: npm run build
